--liquibase formatted sql

--changeset TimurKhamzin:1
--comment first migration

CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role       VARCHAR(32)   NOT NULL,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP,
    enabled    BOOLEAN       NOT NULL,
    username   VARCHAR(64)   NOT NULL UNIQUE,
    password   varchar(1024) NOT NULL
);


CREATE TABLE IF NOT EXISTS user_friends
(
    user_id   BIGINT REFERENCES users (id) NOT NULL,
    friend_id BIGINT REFERENCES users (id) NOT NULL,
    UNIQUE (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS user_subscribers
(
    user_id       BIGINT REFERENCES users (id) NOT NULL,
    subscriber_id BIGINT REFERENCES users (id) NOT NULL,
    UNIQUE (user_id, subscriber_id)
);

CREATE TABLE IF NOT EXISTS user_subscriptions
(
    subscription_id BIGINT REFERENCES users (id) NOT NULL,
    user_id         BIGINT REFERENCES users (id) NOT NULL,
    UNIQUE (subscription_id, user_id)
);

CREATE TABLE IF NOT EXISTS post
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    header     VARCHAR(100)                 NOT NULL,
    text       VARCHAR(500)                 NOT NULL,
    created_at TIMESTAMP                    NOT NULL,
    updated_at TIMESTAMP,
    images     oid,
    author_id  BIGINT REFERENCES users (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status       VARCHAR(32)                  NOT NULL,
    type         VARCHAR(32)                  NOT NULL,
    recipient_id BIGINT REFERENCES users (id) NOT NULL,
    sender_id    BIGINT REFERENCES users (id) NOT NULL,
    UNIQUE (recipient_id, sender_id)
);